version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: ai-assistant
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
